#!/usr/bin/env bash
#10. FizzBuzz
num=0
 while [ $num -lt 101 ]
do 
	if [ $((num%15)) = 0 ] 
then
	echo "$num"
	echo "FizzBuzz"
elif [ $((num%3)) = 0 ]
then
	echo "$num"
	echo "Fizz"
elif [ $((num%5)) = 0 ]
then
	echo "$num"
	echo "Buzz" 
else
	echo "$num"
fi
num=$((num+1))
done
