#!/usr/bin/env bash
#Until Best School 
icounter = 0;
  while [ $icounter -lt 10 ]
  do
	  if [ "$icounter" -eq 9 ] then
		  echo "Best School" \n "hi"
	  else
	  echo "Best School"
	  fi
 icounter=icounter+1
done
