#!/usr/bin/env bash
#Until Best School 
icounter=1;
a=10
while [ "$icounter" -lt "$a" ]
do
     	if [ "$icounter" -eq 9 ]
       	then
	      printf "Best School\nHi\n"
	fi
        echo "Best School"
	icounter=$((icounter+1))
done
