#!/usr/bin/env bash
#5. 4 bad luck, 8 is your chance
icount=1
a=10;
while [ "$icount" -lt "$a" ]
do	
	if [[ $icount -eq 4 ]]
	then
        	echo "bad luck"
        elif [[ $icount -eq 8 ]]
	then 
               echo "good luck"
        else 
	       echo "Best School"
	fi       
	icount=$((icount+1))

done
