#!/usr/bin/env bash
#manage my process
case "$1" in
        start)
                ./manage_my_process &
               touch /var/run/my_process.pid
                echo "$!" > /var/run/my_process.pid
               echo manage_my_process started
                ;;
        stop)
                kill /var/run/my_process.pid
                rm /var/run/my_process.pid
                echo "manage_my_process stopped"
                ;;
        restart)
                kill /var/run/my_process.pid
                rm /var/run/my_process.pid
                ./manage_my_process &
                touch /var/run/my_process.pid
                echo "$!" > /var/run/my_process.pid
                echo "manage_my_process restarted"

                ;;
        *)
                echo $"Usage: manage_my_process${0} {start|stop|restart}"
                exit 5
esac
exit $?
